services:
  puppeteer:
    image: regurusuuu/puppeteer
    container_name: puppeteer
    platform: linux/x86_64
    build:
      context: ./
    volumes:
      - ./src:/workspace/src
    tty: true
    networks:
      default:
        ipv4_address: 172.30.0.2
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: "172.30.0.0/24"
