version: '3.8'
services:
  puppeteer:
    image: sci01708/puppeteer
    container_name: puppeteer
    build:
      context: ./
      args:
        - http_proxy=http://webgate-1.office.nifty.co.jp:8080
        - https_proxy=http://webgate-1.office.nifty.co.jp:8080
        - HTTP_PROXY=http://webgate-1.office.nifty.co.jp:8080
        - HTTPS_PROXY=http://webgate-1.office.nifty.co.jp:8080
    env_file:
      - ./.env
    volumes:
      - ./src:/workspace/src
    tty: true
    networks:
      default:
        ipv4_address: 172.19.0.2
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: "172.19.0.0/24"