version: '3.8'
services:
  puppeteer:
    image: regurusuuu/puppeteer
    container_name: puppeteer
    build:
      context: ./
    volumes:
      - ./src:/workspace/src
    tty: true
    networks:
      default:
        ipv4_address: 172.19.0.2
networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: "172.19.0.0/24"